### PR TITLE
Improve roadmarking system

### PR DESCRIPTION
**Pull request by Thomas--S**
Please review this.

### CODE REVIEW

**Comment by webdesigner97** [comment]
Do you have a short summary about what you changed?

**Comment by cheapie** [comment]
Seems to work for me, but I'd like @webdesigner97 to review it as well before merging.

**Comment by webdesigner97** [comment]
From what I have seen, it's working. Maybe add a short documentation about the new registration system to the wiki?

**Comment by Thomas--S** [comment]
@webdesigner97 I will do so.

**Comment by Thomas--S** [comment]
Here you are: https://github.com/webdesigner97/streets/wiki/Development#roadmarkings-registration

**Comment by webdesigner97** [comment]
Ok, thank you. So the markings are plain white/yellow now?

---- Thomas--S schrieb ----

Here you are: https://github.com/webdesigner97/streets/wiki/Development#roadmarkings-registration

---

**Comment by Thomas--S** [comment]
The white texture still has the same noise as before.

**Comment by webdesigner97** [comment]
Ok

**Comment by Thomas--S** [comment]
@webdesigner97, @cheapie: Is this ok for you now and can it be merged?

**Comment by webdesigner97** [comment]
Yep

**Pull request merged**
