### PR TITLE
Improve Sign Workshop Formspec to avoid too long tabheaders.

### PR DESCRIPTION
**Pull request by Thomas--S**
I made this a PR, so that @cheapie or @webdesigner97  can approve this.

### CODE REVIEW

**Comment by cheapie** [comment]
Define "too long" - it was scrolling fine for me.

**Comment by Thomas--S** [comment]
When the tabheader was longer than the form area, there was kind of the possibility to scroll, but it isn't a really good scrolling thing. The scroll arrow buttons are really small and the tabheader always jumps to the beginning, so you don't see the focused tab. It was in general a quite bad user experience.

**Comment by cheapie** [comment]
I'll take a look when I get home and see if it's any easier to use.

**Comment by Thomas--S** [comment]
Ok. Thanks.

**Comment by Thomas--S** [comment]
@cheapie, @webdesigner97: Can you please review this?

**Comment by Thomas--S** [comment]
@cheapie, @webdesigner97: If there are no complaints until 1st of August, I will merge it then.

**Comment by webdesigner97** [comment]
Sry, I'm quite busy these days. Would be OK for me...

Von meinem Sony Xperia™-Smartphone gesendet

---- Thomas--S schrieb ----

@cheapie, @webdesigner97: If there are no complaints until 1st of August, I will merge it then.

---

**Comment by Thomas--S** [comment]
Ok. Thanks for the answer. Let's wait for @cheapie now.

**Comment by cheapie** [comment]
I've been too busy to do much, but it should be fine from the bit I did see.

**Comment by Thomas--S** [comment]
Thank you very much!

**Comment by webdesigner97** [comment]
I'll continue dev asap

Von meinem Sony Xperia™-Smartphone gesendet

---- Thomas--S schrieb ----

Ok. Thanks for the answer. Let's wait for @cheapie now.

---

**Pull request merged**
