### PR TITLE
Add protection support to manual bollard

### PR DESCRIPTION
**Pull request by Thomas--S**

### CODE REVIEW

**Comment by cheapie** [comment]
On the basis of "looks good and I'm assuming you tested it", merging.

**Comment by Thomas--S** [comment]
I didn't test it enormously, but I tested it quickly.

**Comment by webdesigner97** [comment]
Thank you, I didn't deal with the protection system yet, so I'm glad you know it ;)

**Comment by Thomas--S** [comment]
No problem. BTW, may I get a collaborator of this project maybe?

**Comment by webdesigner97** [comment]
I'm pretty sure we can do that. Do you agree, @cheapie?

Von meinem Sony Xperia™-Smartphone gesendet

---- Thomas--S schrieb ----

No problem. BTW, may I get a collaborator of this project maybe?

---

**Comment by Thomas--S** [comment]
Thank you very much, @webdesigner97.

**Comment by cheapie** [comment]
It should be fine, especially seeing as how the poles dispute has been resolved.

**Comment by webdesigner97** [comment]
Yep! I'll add you to the contributors when I'm on the PC.

Von meinem Sony Xperia™-Smartphone gesendet

---- cheapie schrieb ----

It should be fine, especially seeing as how the poles dispute has been resolved.

---

**Comment by Thomas--S** [comment]
Thank you very much. I will still submit controversial commits via PR.

**Pull request merged**
