### PR TITLE
Add protection support for digiline channel.

### PR DESCRIPTION
**Pull request by Thomas--S**
Will prevent griefing.

### CODE REVIEW

**Comment by webdesigner97** [comment]
I can't review/merge any PRs anymore today because we've got a thunderstorm here and I don't want to risk any data loss. I'll do this tomorrow morning...

**Comment by cheapie** [comment]
You'll need to add "sender" to the function arguments for the on_receive_fields on the lane use signals.

**Comment by Thomas--S** [comment]
Thanks, @cheapie.
PR is updated.

**Comment by cheapie** [comment]
Looks like it works.

**Pull request merged**
