### PR TITLE
Add a traffic barrier and a blinking light.

### LINKED ISSUE #61: Traffic barriers

### PR DESCRIPTION
**Pull request by Thomas--S**
Requires #67 for crafting recipe.
Closes #61 
Solves part of #57

### CODE REVIEW

**Comment by cheapie** [comment]
Any chance you could change the light to use animated textures?

**Comment by Thomas--S** [comment]
During development, I tried animated textures, but it looks very weird, as the turned-off light also emits light. If you are worried about performance, my version shouldn't be such bad, because it uses nodetimers instead of ABMs.

**Comment by cheapie** [comment]
I suppose nodetimers are good enough (we really need something better client-side for this sort of thing, but that's the engine's problem).

Can you make a bit more differentiation between the light and dark textures and hide the "on" version from the creative inventory?

**Comment by Thomas--S** [comment]
ok. I will update the PR in about half a day.

**Comment by webdesigner97** [comment]
Sounds good!

**Comment by Thomas--S** [comment]
PR is updated

**Comment by webdesigner97** [comment]
I would prefer the barrier to look less like a wall and more like this:



What do you think?

**Comment by cheapie** [comment]
Perhaps we could have both? Wall-ish barriers do have their uses, just like the portable one in the picture.

**Comment by Thomas--S** [comment]
The fence-like was on my todo-list anyways. They will be made soon.

**Pull request merged**
