### PR TITLE
Changes the streetpoles to connected nodeboxes.

### PR DESCRIPTION
**Pull request by Thomas--S**
Connects to everything.

### CODE REVIEW

**Comment by webdesigner97** [comment]
Will test this later, thank you.

**Comment by Thomas--S** [comment]
No problem

**Comment by cheapie** [comment]
This makes poles attach to *everything* - including things they shouldn't, such as the road's shoulder or a  nearby wall.

**Comment by Thomas--S** [comment]
@cheapie: I will change this PR soon to solve the problem you mentioned.

**Comment by Thomas--S** [comment]
@cheapie PR is updated.

**Comment by cheapie** [comment]
Well, the straight pole is working, but I'm not sure how good of an idea it is to be using these connecting nodeboxes at all for poles. It might make building some things easier, but it takes away so much control that some other things become impossible to build.

I'll merge this if you add at least the old pole shapes back in, and preferably a few more.

**Comment by Thomas--S** [comment]
Ok. I will update this PR in about half a day.

**Comment by Thomas--S** [comment]
@cheapie Can you please review?

**Comment by cheapie** [comment]
I can later today (~5 hours).

**Comment by Thomas--S** [comment]
Ok. Thanks.

**Comment by webdesigner97** [comment]
The problem with this system is the fact that it does not connect to what we expect it to connect to (and vice-versa). The current connects_to table doesn't let the poles stand on grass but they connect to tree trunks. This not what we expect... 
Although I like the base concept, I have to admit that the current implementation of connected nodeboxes is too inflexible for our poles.

**Comment by cheapie** [comment]
I think I'm probably on wd97's side here. It's more practical to just give the user a set of "building block" pole pieces than to try to have the game guess what they want.

On this note, PRs adding more shapes of pole would be welcomed. These are the most useful ones I can think of at the moment:

1. 4-way intersection, with 0, 1, or 2 more "branches" coming out the front/back
2. Corner with branch(es) (as above)

**Comment by Thomas--S** [comment]
Ok. I will update later.

**Comment by Thomas--S** [comment]
I will close this PR and add new pole shapes later.

**Pull request closed without merging**
